# Site settings
title: SF-LI Blog
SEOTitle: Shufei的博客 | SF Blog
header-img: img/home-bg-o.jpg
email: lsfshufei@163.com
description: "There are no shortcuts to any place worth going."
keyword: "SF, SF Blog, 树飞的博客, 树飞, shufei, Augmented Reality, AR, Computer Vision, CV, OpenCV"
url: "http://lisatiy.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Lisatiy/lisatiy.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Fear not for the future, weep not for the past."
sidebar-avatar: /img/about-me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     lisatiy
zhihu_username:     lasity
github_username:    Lisatiy
# csdn_username:      lisatiy
# facebook_username:  shufei
# jianshu_username:   shufei
# twitter_username:   shufei




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]
# plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: lishufei

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: edffcb39fcbbc0a557f0                            #生成的clientID
  clientSecret: 8e92ec691bc52dbccbd03a4af6995ca763421e7d    #生成的clientSecret
  repo: lisatiy.github.io    #仓库名称
  owner: Lisatiy    #github用户名
  admin: Lisatiy
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计
# Analytics settings
# Baidu Analytics
ba_track_id: 8efdccdafd1a73edf98f8d8d118f3930

# Google Analytics
ga_track_id: 'UA-162688140-1'            # Format: UA-xxxxxx-xx
ga_domain: lishufei.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "谷歌学术",
        href: "https://scholar.google.com.hk/?hl=zh-CN"
    },{
        title: "CSDN·SF",
        href: "https://blog.csdn.net/Lisatiy"
    },{
        title: "PolyU",
        href: "https://www.polyu.edu.hk/ise/"
 #    },{
 #        title: "Apple Developer",
 #        href: "https://developer.apple.com/"
    }
]
